spring.application.name=backend
server.port=8082
server.address=0.0.0.0
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/VentasDB?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true


app.upload.dir=${APP_UPLOAD_DIR:./uploads}
spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=10MB

#configuracion del sistema de asistencia
#url del microservicio de asistencia
asistencia.api.url=http://localhost:8080

#token de seguridad para el microservicio de asistencia
asistencia.api.token=45k34hJ0HVjoNU12ksHNTQjenTaIvsGk2KEblZKleaU

#clave para acceso de administradores
admin.clave=${ADMIN_CLAVE:chiokore123}
